-- ============================================
-- PIZZA ORDERING SAAS - COMPLETE DATABASE SCHEMA
-- Generated by Blink SaaS Probe
-- ============================================

-- Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- ============================================
-- CORE BUSINESS TABLES
-- ============================================

-- Customers (extends auth users with business-specific data)
CREATE TABLE IF NOT EXISTS customers (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id UUID REFERENCES users(id) ON DELETE CASCADE,

  -- Profile
  first_name VARCHAR(100),
  last_name VARCHAR(100),
  phone VARCHAR(20),
  email VARCHAR(255) NOT NULL,

  -- Loyalty
  loyalty_points INTEGER DEFAULT 0,
  total_orders INTEGER DEFAULT 0,
  total_spent DECIMAL(10,2) DEFAULT 0,

  -- Preferences
  default_address_id UUID,
  favorite_items JSONB DEFAULT '[]',
  dietary_restrictions JSONB DEFAULT '[]',

  -- Timestamps
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  last_order_at TIMESTAMP
);

-- Customer Addresses
CREATE TABLE IF NOT EXISTS customer_addresses (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  customer_id UUID REFERENCES customers(id) ON DELETE CASCADE,

  label VARCHAR(50) DEFAULT 'Home', -- Home, Work, Other
  street_address VARCHAR(255) NOT NULL,
  apartment VARCHAR(50),
  city VARCHAR(100) NOT NULL,
  state VARCHAR(50) NOT NULL,
  zip_code VARCHAR(20) NOT NULL,

  delivery_instructions TEXT,
  is_default BOOLEAN DEFAULT false,

  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Menu Categories
CREATE TABLE IF NOT EXISTS menu_categories (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  name VARCHAR(100) NOT NULL,
  description TEXT,
  display_order INTEGER DEFAULT 0,
  image_url VARCHAR(500),
  is_active BOOLEAN DEFAULT true,

  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Menu Items (Pizzas, Sides, Drinks, Desserts)
CREATE TABLE IF NOT EXISTS menu_items (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  category_id UUID REFERENCES menu_categories(id) ON DELETE SET NULL,

  name VARCHAR(200) NOT NULL,
  description TEXT,

  -- Pricing (base price, size/variant pricing in options)
  base_price DECIMAL(8,2) NOT NULL,

  -- Images
  image_url VARCHAR(500),
  thumbnail_url VARCHAR(500),

  -- Metadata
  is_featured BOOLEAN DEFAULT false,
  is_available BOOLEAN DEFAULT true,
  is_popular BOOLEAN DEFAULT false,

  -- Dietary flags
  is_vegetarian BOOLEAN DEFAULT false,
  is_vegan BOOLEAN DEFAULT false,
  is_gluten_free BOOLEAN DEFAULT false,

  -- Customization
  allows_customization BOOLEAN DEFAULT true,
  max_toppings INTEGER DEFAULT 10,

  -- Stats
  times_ordered INTEGER DEFAULT 0,
  avg_rating DECIMAL(3,2) DEFAULT 0,
  review_count INTEGER DEFAULT 0,

  -- Timestamps
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Item Sizes/Variants (Small, Medium, Large, XL for pizzas)
CREATE TABLE IF NOT EXISTS item_variants (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  item_id UUID REFERENCES menu_items(id) ON DELETE CASCADE,

  name VARCHAR(50) NOT NULL, -- 'Small', 'Medium', 'Large', 'XL'
  price_modifier DECIMAL(8,2) DEFAULT 0, -- Added to base_price
  serves VARCHAR(50), -- '1-2 people', '2-3 people', etc.

  is_default BOOLEAN DEFAULT false,
  is_available BOOLEAN DEFAULT true,
  display_order INTEGER DEFAULT 0,

  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Toppings / Modifiers
CREATE TABLE IF NOT EXISTS toppings (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),

  name VARCHAR(100) NOT NULL,
  category VARCHAR(50) DEFAULT 'topping', -- 'topping', 'sauce', 'cheese', 'crust'
  price DECIMAL(6,2) DEFAULT 0,

  is_premium BOOLEAN DEFAULT false,
  is_available BOOLEAN DEFAULT true,

  -- Dietary
  is_vegetarian BOOLEAN DEFAULT true,
  is_vegan BOOLEAN DEFAULT false,

  display_order INTEGER DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ============================================
-- ORDER MANAGEMENT
-- ============================================

-- Orders
CREATE TABLE IF NOT EXISTS orders (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  order_number VARCHAR(20) UNIQUE NOT NULL, -- Human-readable: ORD-20240115-001
  customer_id UUID REFERENCES customers(id),

  -- Status workflow
  status VARCHAR(30) DEFAULT 'pending',
  -- pending -> confirmed -> preparing -> ready -> out_for_delivery -> delivered
  -- OR: pending -> confirmed -> preparing -> ready -> picked_up (for pickup orders)
  -- OR: pending -> cancelled

  -- Order type
  order_type VARCHAR(20) DEFAULT 'delivery', -- delivery, pickup, dine_in

  -- Timing
  is_scheduled BOOLEAN DEFAULT false,
  scheduled_for TIMESTAMP,
  estimated_ready_at TIMESTAMP,
  estimated_delivery_at TIMESTAMP,

  -- Delivery info (null for pickup)
  delivery_address_id UUID REFERENCES customer_addresses(id),
  delivery_address_snapshot JSONB, -- Frozen copy at order time
  delivery_fee DECIMAL(6,2) DEFAULT 0,

  -- Pricing
  subtotal DECIMAL(10,2) NOT NULL,
  tax_amount DECIMAL(10,2) DEFAULT 0,
  tip_amount DECIMAL(10,2) DEFAULT 0,
  discount_amount DECIMAL(10,2) DEFAULT 0,
  total_amount DECIMAL(10,2) NOT NULL,

  -- Payment
  payment_status VARCHAR(20) DEFAULT 'pending', -- pending, paid, refunded, failed
  payment_method VARCHAR(30), -- card, cash, apple_pay, google_pay
  stripe_payment_intent_id VARCHAR(100),

  -- Promo/Discounts
  promo_code_id UUID,
  promo_code_used VARCHAR(50),

  -- Customer notes
  special_instructions TEXT,

  -- Metadata
  source VARCHAR(30) DEFAULT 'web', -- web, mobile_app, phone, in_store
  ip_address VARCHAR(45),
  user_agent TEXT,

  -- Timestamps
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  confirmed_at TIMESTAMP,
  prepared_at TIMESTAMP,
  ready_at TIMESTAMP,
  delivered_at TIMESTAMP,
  cancelled_at TIMESTAMP,
  cancellation_reason TEXT
);

-- Order Items
CREATE TABLE IF NOT EXISTS order_items (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  order_id UUID REFERENCES orders(id) ON DELETE CASCADE,
  menu_item_id UUID REFERENCES menu_items(id),
  variant_id UUID REFERENCES item_variants(id),

  -- Snapshot (frozen at order time)
  item_name VARCHAR(200) NOT NULL,
  variant_name VARCHAR(50),

  quantity INTEGER DEFAULT 1,
  unit_price DECIMAL(8,2) NOT NULL,
  total_price DECIMAL(10,2) NOT NULL,

  -- Customizations
  special_instructions TEXT,

  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Order Item Toppings (customizations)
CREATE TABLE IF NOT EXISTS order_item_toppings (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  order_item_id UUID REFERENCES order_items(id) ON DELETE CASCADE,
  topping_id UUID REFERENCES toppings(id),

  topping_name VARCHAR(100) NOT NULL, -- Snapshot
  quantity INTEGER DEFAULT 1, -- For double/triple toppings
  price DECIMAL(6,2) DEFAULT 0,

  modifier_type VARCHAR(20) DEFAULT 'add', -- add, remove, extra, light

  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Order Status History (audit trail)
CREATE TABLE IF NOT EXISTS order_status_history (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  order_id UUID REFERENCES orders(id) ON DELETE CASCADE,

  status VARCHAR(30) NOT NULL,
  changed_by UUID, -- staff user_id or null for system
  notes TEXT,

  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ============================================
-- PROMOTIONS & LOYALTY
-- ============================================

-- Promo Codes
CREATE TABLE IF NOT EXISTS promo_codes (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  code VARCHAR(50) UNIQUE NOT NULL,

  description TEXT,
  discount_type VARCHAR(20) NOT NULL, -- percentage, fixed, free_item
  discount_value DECIMAL(8,2) NOT NULL, -- 10 for 10% or $10

  -- Conditions
  minimum_order DECIMAL(8,2) DEFAULT 0,
  max_discount DECIMAL(8,2), -- Cap for percentage discounts

  -- Limits
  max_uses INTEGER,
  uses_count INTEGER DEFAULT 0,
  max_uses_per_customer INTEGER DEFAULT 1,

  -- Validity
  valid_from TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  valid_until TIMESTAMP,
  is_active BOOLEAN DEFAULT true,

  -- Targeting
  first_order_only BOOLEAN DEFAULT false,
  applicable_items JSONB, -- null = all items

  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Customer Promo Code Uses
CREATE TABLE IF NOT EXISTS customer_promo_uses (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  customer_id UUID REFERENCES customers(id) ON DELETE CASCADE,
  promo_code_id UUID REFERENCES promo_codes(id) ON DELETE CASCADE,
  order_id UUID REFERENCES orders(id),

  used_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

  UNIQUE(customer_id, promo_code_id, order_id)
);

-- ============================================
-- REVIEWS & RATINGS
-- ============================================

CREATE TABLE IF NOT EXISTS reviews (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  order_id UUID REFERENCES orders(id) ON DELETE CASCADE,
  customer_id UUID REFERENCES customers(id) ON DELETE CASCADE,
  menu_item_id UUID REFERENCES menu_items(id),

  rating INTEGER NOT NULL CHECK (rating >= 1 AND rating <= 5),
  review_text TEXT,

  -- Response
  staff_response TEXT,
  responded_at TIMESTAMP,

  is_verified BOOLEAN DEFAULT true, -- Verified purchase
  is_visible BOOLEAN DEFAULT true,

  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ============================================
-- STAFF & OPERATIONS
-- ============================================

-- Staff members (extends users)
CREATE TABLE IF NOT EXISTS staff (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id UUID REFERENCES users(id) ON DELETE CASCADE,

  role VARCHAR(30) NOT NULL, -- owner, manager, cook, driver, cashier

  first_name VARCHAR(100) NOT NULL,
  last_name VARCHAR(100) NOT NULL,
  phone VARCHAR(20),

  is_active BOOLEAN DEFAULT true,
  hire_date DATE,

  -- For drivers
  vehicle_info JSONB,
  current_location JSONB, -- lat, lng for live tracking

  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Delivery Assignments
CREATE TABLE IF NOT EXISTS deliveries (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  order_id UUID REFERENCES orders(id) ON DELETE CASCADE,
  driver_id UUID REFERENCES staff(id),

  status VARCHAR(30) DEFAULT 'assigned', -- assigned, picked_up, in_transit, delivered, failed

  picked_up_at TIMESTAMP,
  delivered_at TIMESTAMP,

  -- Tracking
  route_distance DECIMAL(8,2), -- miles
  actual_duration INTEGER, -- minutes

  -- Customer feedback
  delivery_rating INTEGER CHECK (delivery_rating >= 1 AND delivery_rating <= 5),
  delivery_feedback TEXT,

  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ============================================
-- STORE SETTINGS & CONFIG
-- ============================================

CREATE TABLE IF NOT EXISTS store_settings (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  key VARCHAR(100) UNIQUE NOT NULL,
  value JSONB NOT NULL,

  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_by UUID
);

-- Default store settings to insert:
-- tax_rate: 0.08 (8%)
-- delivery_fee: 4.99
-- minimum_order: 15.00
-- delivery_radius_miles: 5
-- estimated_prep_time_minutes: 25
-- store_hours: { mon: {open: "11:00", close: "22:00"}, ... }
-- accepts_cash: true
-- accepts_card: true

-- ============================================
-- ANALYTICS TABLES
-- ============================================

-- Daily Sales Summary (for fast dashboard queries)
CREATE TABLE IF NOT EXISTS daily_sales (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  date DATE UNIQUE NOT NULL,

  total_orders INTEGER DEFAULT 0,
  completed_orders INTEGER DEFAULT 0,
  cancelled_orders INTEGER DEFAULT 0,

  gross_sales DECIMAL(12,2) DEFAULT 0,
  net_sales DECIMAL(12,2) DEFAULT 0, -- After discounts
  tax_collected DECIMAL(10,2) DEFAULT 0,
  tips_collected DECIMAL(10,2) DEFAULT 0,
  delivery_fees DECIMAL(10,2) DEFAULT 0,

  avg_order_value DECIMAL(8,2) DEFAULT 0,

  new_customers INTEGER DEFAULT 0,
  returning_customers INTEGER DEFAULT 0,

  -- By order type
  delivery_orders INTEGER DEFAULT 0,
  pickup_orders INTEGER DEFAULT 0,
  dine_in_orders INTEGER DEFAULT 0,

  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ============================================
-- INDEXES FOR PERFORMANCE
-- ============================================

CREATE INDEX IF NOT EXISTS idx_orders_customer ON orders(customer_id);
CREATE INDEX IF NOT EXISTS idx_orders_status ON orders(status);
CREATE INDEX IF NOT EXISTS idx_orders_created ON orders(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_orders_order_number ON orders(order_number);
CREATE INDEX IF NOT EXISTS idx_order_items_order ON order_items(order_id);
CREATE INDEX IF NOT EXISTS idx_menu_items_category ON menu_items(category_id);
CREATE INDEX IF NOT EXISTS idx_customers_email ON customers(email);
CREATE INDEX IF NOT EXISTS idx_customers_user ON customers(user_id);
CREATE INDEX IF NOT EXISTS idx_deliveries_driver ON deliveries(driver_id);
CREATE INDEX IF NOT EXISTS idx_daily_sales_date ON daily_sales(date DESC);

-- ============================================
-- FUNCTIONS & TRIGGERS
-- ============================================

-- Auto-generate order number
CREATE OR REPLACE FUNCTION generate_order_number()
RETURNS TRIGGER AS $$
BEGIN
  NEW.order_number := 'ORD-' || TO_CHAR(CURRENT_DATE, 'YYYYMMDD') || '-' ||
    LPAD(CAST((SELECT COUNT(*) + 1 FROM orders WHERE DATE(created_at) = CURRENT_DATE) AS TEXT), 4, '0');
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER set_order_number
  BEFORE INSERT ON orders
  FOR EACH ROW
  WHEN (NEW.order_number IS NULL)
  EXECUTE FUNCTION generate_order_number();

-- Update timestamps
CREATE OR REPLACE FUNCTION update_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = CURRENT_TIMESTAMP;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER update_customers_timestamp
  BEFORE UPDATE ON customers
  FOR EACH ROW EXECUTE FUNCTION update_updated_at();

CREATE TRIGGER update_menu_items_timestamp
  BEFORE UPDATE ON menu_items
  FOR EACH ROW EXECUTE FUNCTION update_updated_at();

CREATE TRIGGER update_menu_categories_timestamp
  BEFORE UPDATE ON menu_categories
  FOR EACH ROW EXECUTE FUNCTION update_updated_at();

-- Record order status changes
CREATE OR REPLACE FUNCTION record_status_change()
RETURNS TRIGGER AS $$
BEGIN
  IF OLD.status IS DISTINCT FROM NEW.status THEN
    INSERT INTO order_status_history (order_id, status)
    VALUES (NEW.id, NEW.status);

    -- Update timestamps based on status
    IF NEW.status = 'confirmed' THEN NEW.confirmed_at = CURRENT_TIMESTAMP;
    ELSIF NEW.status = 'ready' THEN NEW.ready_at = CURRENT_TIMESTAMP;
    ELSIF NEW.status = 'delivered' OR NEW.status = 'picked_up' THEN NEW.delivered_at = CURRENT_TIMESTAMP;
    ELSIF NEW.status = 'cancelled' THEN NEW.cancelled_at = CURRENT_TIMESTAMP;
    END IF;
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER track_order_status
  BEFORE UPDATE ON orders
  FOR EACH ROW EXECUTE FUNCTION record_status_change();

-- Update customer stats after order completion
CREATE OR REPLACE FUNCTION update_customer_stats()
RETURNS TRIGGER AS $$
BEGIN
  IF NEW.status = 'delivered' OR NEW.status = 'picked_up' THEN
    UPDATE customers SET
      total_orders = total_orders + 1,
      total_spent = total_spent + NEW.total_amount,
      last_order_at = CURRENT_TIMESTAMP,
      loyalty_points = loyalty_points + FLOOR(NEW.total_amount)
    WHERE id = NEW.customer_id;
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER update_customer_on_order_complete
  AFTER UPDATE ON orders
  FOR EACH ROW
  WHEN (OLD.status IS DISTINCT FROM NEW.status)
  EXECUTE FUNCTION update_customer_stats();
