/**
 * Database Setup Script
 * Auto-generated by Module Library Assembler
 * 
 * Run: node setup-db.js
 * This will create all required tables if they don't exist
 */

require('dotenv').config();
const { Pool } = require('pg');

const pool = new Pool({
  connectionString: process.env.DATABASE_URL,
  ssl: process.env.NODE_ENV === 'production' ? { rejectUnauthorized: false } : false
});

const tables = {
  // Users table (auth module)
  users: `
    CREATE TABLE IF NOT EXISTS users (
      id SERIAL PRIMARY KEY,
      email VARCHAR(255) UNIQUE NOT NULL,
      password_hash VARCHAR(255) NOT NULL,
      full_name VARCHAR(255),
      phone VARCHAR(50),
      subscription_tier VARCHAR(50) DEFAULT 'free',
      is_admin BOOLEAN DEFAULT false,
      scans_used INTEGER DEFAULT 0,
      referred_by VARCHAR(50),
      referral_code_id INTEGER,
      referred_at TIMESTAMP,
      reset_token VARCHAR(255),
      reset_token_expires TIMESTAMP,
      created_at TIMESTAMP DEFAULT NOW(),
      updated_at TIMESTAMP DEFAULT NOW()
    )
  `,
  
  // Bookings table (booking module)
  bookings: `
    CREATE TABLE IF NOT EXISTS bookings (
      id SERIAL PRIMARY KEY,
      user_id INTEGER REFERENCES users(id),
      customer_name VARCHAR(255) NOT NULL,
      customer_email VARCHAR(255),
      customer_phone VARCHAR(50),
      service_type VARCHAR(100) DEFAULT 'general',
      booking_date DATE NOT NULL,
      start_time TIME NOT NULL,
      end_time TIME,
      party_size INTEGER DEFAULT 1,
      notes TEXT,
      status VARCHAR(50) DEFAULT 'pending',
      cancellation_reason TEXT,
      cancelled_at TIMESTAMP,
      created_at TIMESTAMP DEFAULT NOW(),
      updated_at TIMESTAMP DEFAULT NOW()
    )
  `,
  
  // Contact submissions
  contact_submissions: `
    CREATE TABLE IF NOT EXISTS contact_submissions (
      id SERIAL PRIMARY KEY,
      name VARCHAR(255) NOT NULL,
      email VARCHAR(255) NOT NULL,
      phone VARCHAR(50),
      subject VARCHAR(255),
      message TEXT NOT NULL,
      status VARCHAR(50) DEFAULT 'new',
      responded_at TIMESTAMP,
      created_at TIMESTAMP DEFAULT NOW()
    )
  `,
  
  // Referral codes (auth module)
  referral_codes: `
    CREATE TABLE IF NOT EXISTS referral_codes (
      id SERIAL PRIMARY KEY,
      code VARCHAR(50) UNIQUE NOT NULL,
      user_id INTEGER REFERENCES users(id),
      total_signups INTEGER DEFAULT 0,
      active BOOLEAN DEFAULT true,
      created_at TIMESTAMP DEFAULT NOW(),
      updated_at TIMESTAMP DEFAULT NOW()
    )
  `,
  
  // Services/Products
  services: `
    CREATE TABLE IF NOT EXISTS services (
      id SERIAL PRIMARY KEY,
      name VARCHAR(255) NOT NULL,
      description TEXT,
      price DECIMAL(10, 2),
      duration_minutes INTEGER,
      category VARCHAR(100),
      active BOOLEAN DEFAULT true,
      created_at TIMESTAMP DEFAULT NOW(),
      updated_at TIMESTAMP DEFAULT NOW()
    )
  `,
  
  // Reviews/Testimonials
  reviews: `
    CREATE TABLE IF NOT EXISTS reviews (
      id SERIAL PRIMARY KEY,
      user_id INTEGER REFERENCES users(id),
      booking_id INTEGER REFERENCES bookings(id),
      rating INTEGER CHECK (rating >= 1 AND rating <= 5),
      title VARCHAR(255),
      content TEXT,
      approved BOOLEAN DEFAULT false,
      created_at TIMESTAMP DEFAULT NOW()
    )
  `,
  
  // Newsletter subscribers
  subscribers: `
    CREATE TABLE IF NOT EXISTS subscribers (
      id SERIAL PRIMARY KEY,
      email VARCHAR(255) UNIQUE NOT NULL,
      name VARCHAR(255),
      subscribed BOOLEAN DEFAULT true,
      created_at TIMESTAMP DEFAULT NOW()
    )
  `
};

async function setupDatabase() {
  console.log('🗄️  Setting up database...\n');

  try {
    // Test connection
    await pool.query('SELECT NOW()');
    console.log('✅ Database connected\n');

    // Create each table
    for (const [tableName, createSQL] of Object.entries(tables)) {
      try {
        await pool.query(createSQL);
        console.log(`✅ Table "${tableName}" ready`);
      } catch (err) {
        console.error(`❌ Failed to create "${tableName}":`, err.message);
      }
    }

    // Create indexes for performance
    console.log('\n📊 Creating indexes...');

    const indexes = [
      'CREATE INDEX IF NOT EXISTS idx_users_email ON users(email)',
      'CREATE INDEX IF NOT EXISTS idx_bookings_date ON bookings(booking_date)',
      'CREATE INDEX IF NOT EXISTS idx_bookings_user ON bookings(user_id)',
      'CREATE INDEX IF NOT EXISTS idx_bookings_status ON bookings(status)',
      'CREATE INDEX IF NOT EXISTS idx_contact_status ON contact_submissions(status)'
    ];

    for (const idx of indexes) {
      try {
        await pool.query(idx);
      } catch (err) {
        // Index might already exist, that's fine
      }
    }
    console.log('✅ Indexes created\n');

    // Seed admin user if ADMIN_EMAIL and ADMIN_PASSWORD are set
    await seedAdminUser();

    // Summary
    const tableCount = await pool.query(`
      SELECT COUNT(*) FROM information_schema.tables
      WHERE table_schema = 'public'
    `);

    console.log('═══════════════════════════════════════');
    console.log(`✅ Database setup complete!`);
    console.log(`   Tables: ${tableCount.rows[0].count}`);
    console.log('═══════════════════════════════════════\n');

  } catch (error) {
    console.error('❌ Database setup failed:', error.message);
    process.exit(1);
  } finally {
    await pool.end();
  }
}

/**
 * Seed admin user from environment variables
 * Only creates if ADMIN_EMAIL and ADMIN_PASSWORD are set
 */
async function seedAdminUser() {
  const adminEmail = process.env.ADMIN_EMAIL;
  const adminPassword = process.env.ADMIN_PASSWORD;

  if (!adminEmail || !adminPassword) {
    console.log('⚠️  ADMIN_EMAIL/ADMIN_PASSWORD not set - skipping admin seeding');
    return;
  }

  console.log('\n👤 Seeding admin user...');

  try {
    // Check if admin already exists
    const existingResult = await pool.query(
      'SELECT id FROM users WHERE email = $1',
      [adminEmail]
    );

    if (existingResult.rows.length > 0) {
      // Update existing admin password
      const bcrypt = require('bcryptjs');
      const passwordHash = await bcrypt.hash(adminPassword, 10);

      await pool.query(
        'UPDATE users SET password_hash = $1, is_admin = true, updated_at = NOW() WHERE email = $2',
        [passwordHash, adminEmail]
      );
      console.log(`✅ Admin user updated: ${adminEmail}`);
    } else {
      // Create new admin user
      const bcrypt = require('bcryptjs');
      const passwordHash = await bcrypt.hash(adminPassword, 10);

      await pool.query(
        `INSERT INTO users (email, password_hash, full_name, is_admin, subscription_tier, created_at, updated_at)
         VALUES ($1, $2, $3, true, 'admin', NOW(), NOW())`,
        [adminEmail, passwordHash, 'Admin']
      );
      console.log(`✅ Admin user created: ${adminEmail}`);
    }
  } catch (err) {
    console.error('⚠️  Could not seed admin user:', err.message);
  }
}

// Run setup
setupDatabase();