/**
 * Lucide Icons Configuration
 * Extracted from server.cjs
 *
 * Whitelist of valid icons and replacement mappings for invalid icons
 */

const VALID_LUCIDE_ICONS = [
  'Activity', 'Airplay', 'AlertCircle', 'AlertTriangle', 'AlignCenter', 'AlignJustify', 'AlignLeft', 'AlignRight',
  'Anchor', 'Aperture', 'Archive', 'ArrowDown', 'ArrowLeft', 'ArrowRight', 'ArrowUp', 'ArrowUpRight', 'ArrowDownRight',
  'Award', 'BarChart', 'BarChart2', 'Battery', 'BatteryCharging', 'Bell', 'BellOff', 'Bluetooth', 'Bold', 'Book',
  'BookOpen', 'Bookmark', 'Box', 'Briefcase', 'Building', 'Building2', 'Calendar', 'Camera', 'CameraOff',
  'Car', 'Check', 'CheckCircle', 'CheckCircle2', 'CheckSquare', 'ChevronDown', 'ChevronLeft', 'ChevronRight',
  'ChevronUp', 'ChevronsDown', 'ChevronsLeft', 'ChevronsRight', 'ChevronsUp', 'Chrome', 'Circle', 'Clipboard',
  'Clock', 'Cloud', 'CloudOff', 'Code', 'Coffee', 'Cog', 'Compass', 'Copy', 'CornerDownLeft', 'CornerDownRight',
  'CreditCard', 'Crop', 'Crosshair', 'Database', 'Delete', 'Disc', 'DollarSign', 'Download', 'Droplet', 'Edit',
  'Edit2', 'Edit3', 'ExternalLink', 'Eye', 'EyeOff', 'Facebook', 'FastForward', 'Feather', 'File', 'FileText',
  'Film', 'Filter', 'Flag', 'Folder', 'FolderOpen', 'Gift', 'GitBranch', 'GitCommit', 'GitMerge', 'Github',
  'Globe', 'Globe2', 'Grid', 'GripVertical', 'Hash', 'Headphones', 'Heart', 'HelpCircle', 'Home', 'Image',
  'Inbox', 'Info', 'Instagram', 'Italic', 'Key', 'Layers', 'Layout', 'LifeBuoy', 'Link', 'Link2', 'Linkedin',
  'List', 'Loader', 'Lock', 'LogIn', 'LogOut', 'Mail', 'Map', 'MapPin', 'Maximize', 'Maximize2', 'Menu',
  'MessageCircle', 'MessageSquare', 'Mic', 'MicOff', 'Minimize', 'Minimize2', 'Minus', 'MinusCircle', 'Monitor',
  'Moon', 'MoreHorizontal', 'MoreVertical', 'Mountain', 'Move', 'Music', 'Navigation', 'Navigation2', 'Octagon',
  'Package', 'Paperclip', 'Pause', 'PauseCircle', 'Pen', 'Percent', 'Phone', 'PhoneCall', 'PhoneIncoming',
  'PhoneOutgoing', 'PieChart', 'Pin', 'Play', 'PlayCircle', 'Plus', 'PlusCircle', 'PlusSquare', 'Pocket',
  'Power', 'Printer', 'Quote', 'Radio', 'RefreshCw', 'Repeat', 'Rewind', 'RotateCcw', 'RotateCw', 'Rss',
  'Save', 'Scissors', 'Search', 'Send', 'Server', 'Settings', 'Settings2', 'Share', 'Share2', 'Shield',
  'ShieldCheck', 'ShoppingBag', 'ShoppingCart', 'Shuffle', 'Sidebar', 'SkipBack', 'SkipForward', 'Slack',
  'Slash', 'Sliders', 'Smartphone', 'Smile', 'Speaker', 'Square', 'Star', 'StopCircle', 'Sun', 'Sunrise',
  'Sunset', 'Tablet', 'Tag', 'Target', 'Terminal', 'Thermometer', 'ThumbsDown', 'ThumbsUp', 'ToggleLeft',
  'ToggleRight', 'Tool', 'Trash', 'Trash2', 'TrendingDown', 'TrendingUp', 'Triangle', 'Truck', 'Tv', 'Twitter',
  'Type', 'Umbrella', 'Underline', 'Unlock', 'Upload', 'UploadCloud', 'User', 'UserCheck', 'UserMinus', 'UserPlus',
  'UserX', 'Users', 'Video', 'VideoOff', 'Voicemail', 'Volume', 'Volume1', 'Volume2', 'VolumeX', 'Watch',
  'Wifi', 'WifiOff', 'Wind', 'X', 'XCircle', 'XSquare', 'Youtube', 'Zap', 'ZapOff', 'ZoomIn', 'ZoomOut',
  'Sparkles', 'Rocket', 'Crown', 'Gem', 'Flame', 'Leaf', 'TreePine', 'Waves', 'Utensils', 'UtensilsCrossed',
  'Trophy', 'Handshake', 'Medal', 'PartyPopper', 'Gamepad2', 'Dumbbell', 'Timer', 'Wallet', 'Receipt', 'Scale',
  'Wine', 'Beer', 'Pizza', 'Sandwich', 'Salad', 'Soup', 'IceCream', 'Cake', 'Cookie', 'Apple', 'Banana',
  'Cherry', 'Grape', 'Citrus', 'Carrot', 'Beef', 'Fish', 'Egg', 'Milk', 'Wheat', 'Croissant', 'Popcorn',
  'Candy', 'Lollipop', 'ChefHat', 'CookingPot', 'Microwave', 'Refrigerator', 'Armchair', 'Bed', 'Bath',
  'Lamp', 'Sofa', 'DoorOpen', 'DoorClosed', 'Warehouse', 'Factory', 'Store', 'Hotel', 'School', 'Church',
  'Hospital', 'Landmark', 'Castle', 'Tent', 'TreeDeciduous', 'Trees', 'Flower', 'Flower2', 'Sprout',
  'Footprints', 'PawPrint', 'Bug', 'Bird', 'Cat', 'Dog', 'Rabbit', 'Squirrel', 'Turtle', 'Fish',
  'Accessibility', 'Baby', 'Backpack', 'Badge', 'Banknote', 'Barcode', 'Baseline', 'Beaker', 'BellRing',
  'Bike', 'Binary', 'Biohazard', 'Blinds', 'Blocks', 'Bluetooth', 'Bomb', 'Bone', 'BookCopy', 'BookMarked',
  'BotMessageSquare', 'Brain', 'BrickWall', 'Brush', 'BugOff', 'BugPlay', 'Calculator', 'CalendarCheck',
  'CalendarClock', 'CalendarDays', 'CalendarHeart', 'CalendarPlus', 'CalendarRange', 'CalendarSearch',
  'CandlestickChart', 'Captions', 'CarFront', 'Caravan', 'CaseLower', 'CaseUpper', 'CassetteTape',
  'Cast', 'ChartArea', 'ChartBar', 'ChartLine', 'ChartPie', 'CircleDot', 'CircleUser', 'Clapperboard',
  'ClipboardCheck', 'ClipboardList', 'ClipboardPen', 'CloudDownload', 'CloudUpload', 'Cloudy', 'Clover',
  'CodeXml', 'Coins', 'Columns', 'Combine', 'Command', 'Component', 'Computer', 'ConciergeBell', 'Cone',
  'Construction', 'Contact', 'Container', 'Contrast', 'Cookie', 'CopyCheck', 'Copyright', 'CornerLeftDown',
  'CornerLeftUp', 'CornerRightDown', 'CornerRightUp', 'CornerUpLeft', 'CornerUpRight', 'Cpu', 'CreativeCommons',
  'Crown', 'Cuboid', 'CupSoda', 'Currency', 'Cylinder',
  // Additional valid icons in lucide-react ^0.454.0
  'Hammer', 'Wrench', 'Paintbrush', 'Palette', 'Ruler', 'Pipette', 'Eraser',
  'PenTool', 'Highlighter', 'Stamp', 'Sticker', 'Wand', 'Wand2',
  'Plane', 'PlaneTakeoff', 'PlaneLanding', 'Ship', 'Sailboat', 'Train', 'Tram', 'Bus',
  'Ambulance', 'FireExtinguisher', 'Siren', 'Construction',
  'Pill', 'Stethoscope', 'Syringe', 'HeartPulse', 'Microscope', 'TestTube', 'Dna',
  'GraduationCap', 'Library', 'BookText', 'NotebookPen', 'FileQuestion',
  'Presentation', 'Projector', 'ScreenShare', 'MonitorPlay',
  'Gamepad', 'Joystick', 'Dice1', 'Dice2', 'Dice3', 'Dice4', 'Dice5', 'Dice6',
  'Piano', 'Guitar', 'Drum', 'Mic2', 'MicVocal', 'Headset',
  'Shirt', 'Watch', 'Glasses', 'Gem', 'Diamond', 'Crown', 'Ring',
  'Martini', 'GlassWater', 'CoffeeIcon', 'Soup', 'Drumstick',
  'Sunrise', 'Sunset', 'CloudRain', 'CloudSnow', 'CloudLightning', 'Snowflake',
  'Palmtree', 'Mountain', 'MountainSnow', 'Waves', 'Rainbow',
  'Fingerprint', 'Scan', 'ScanFace', 'QrCode', 'Barcode',
  'PlugZap', 'Cable', 'Usb', 'HardDrive', 'MemoryStick',
  'ShieldAlert', 'ShieldBan', 'ShieldOff', 'KeyRound', 'KeySquare',
  'Waypoints', 'Route', 'Signpost', 'SignpostBig', 'Milestone'
];

// Icon replacement map for invalid icons
// Note: Icons like Handshake, Trophy, Medal ARE valid in lucide-react ^0.454.0
// Only map truly non-existent or problematic icons
const ICON_REPLACEMENTS = {
  'Rifle': 'Target',
  'Gun': 'Crosshair',
  'Pistol': 'Circle',
  'Bullet': 'Circle',
  'Weapon': 'Shield',
  'Sword': 'Shield',
  'Axe': 'Wrench',
  'Drill': 'Wrench',
  'Saw': 'Wrench',
  'Screwdriver': 'Wrench',
  // Common AI hallucinations - map to valid alternatives
  'Partnership': 'Users',
  'Team': 'Users',
  'Group': 'Users',
  'People': 'Users',
  'Agreement': 'FileText',
  'Contract': 'FileText',
  'Document': 'FileText',
  'Paper': 'FileText',
  'Money': 'DollarSign',
  'Cash': 'Banknote',
  'Price': 'Tag',
  'Cost': 'Receipt',
  'Location': 'MapPin',
  'Address': 'MapPin',
  'Place': 'MapPin',
  'Time': 'Clock',
  'Duration': 'Clock',
  'Schedule': 'Calendar',
  'Date': 'Calendar',
  'Email': 'Mail',
  'Message': 'MessageSquare',
  'Chat': 'MessageSquare',
  'Call': 'Phone',
  'Telephone': 'Phone',
  'Website': 'Globe',
  'Internet': 'Globe',
  'Web': 'Globe',
  'Social': 'Share',
  'Network': 'Share',
  'Success': 'CheckCircle',
  'Complete': 'CheckCircle',
  'Done': 'Check',
  'Error': 'AlertCircle',
  'Warning': 'AlertTriangle',
  'Danger': 'AlertTriangle',
  'Info': 'Info',
  'Help': 'HelpCircle',
  'Question': 'HelpCircle'
};

module.exports = {
  VALID_LUCIDE_ICONS,
  ICON_REPLACEMENTS
};
